<?php

namespace Drupal\webform_image_select;

use Drupal\webprofiler\Entity\ConfigEntityStorageDecorator;
use Drupal\Core\Config\Entity\ConfigEntityStorage;
use Drupal\Core\Serialization\Yaml;

/**
 * This file is auto-generated by the Webprofiler module.
 */
class WebformImageSelectImagesStorageDecorator extends ConfigEntityStorageDecorator implements \Drupal\webform_image_select\WebformImageSelectImagesStorageInterface
{
    public function getCategories()
    {
        return $this->getOriginalObject()->getCategories();
    }
    public function getImages()
    {
        return $this->getOriginalObject()->getImages();
    }
    public function getUsedByWebforms(WebformImageSelectImagesInterface $webform_images)
    {
        return $this->getOriginalObject()->getUsedByWebforms($webform_images);
    }
}
